GPS code for ESP32
robotique-udes/rover_micro pull request #3
Opened 2024-04-30 02:17 UTC by AudeR22

2024-04-30 14:50 UTC, Pmichaud29 requested changes
Quelques commentaires sur l'implémentation et des checks de safety, mais globalement c'est très bien!

2024-04-30 14:50 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +  float latitude = allDegrees + (allMinutes / 60);
/60.0f

2024-04-30 14:50 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +float getLatitude(char latData[], char latSign[])
fixe tes longeurs d'array ou du moins un maximum

2024-04-30 14:50 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +  for (; latData[i] != '\0'; i++)
chances d'overshoot de l'array -> met une condition de sorti juste pour être sur de pas tombé dans une loop infinie, example:
for (; latData[i] != '\0' && i < MAX_SIZE;  i++)

2024-04-30 14:50 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +float getLongitude(char longData[], char longSign[])
Mêmes commentaires que l'autre fonction

2024-04-30 14:50 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +    latitude *= -1;
-1.0f

2024-04-30 14:54 UTC, AudeR22 commented on GPS/platformio.ini
> +    '-D LOGGER_LOWEST_LEVEL=0'
fait

2024-04-30 14:58 UTC, AudeR22 commented on GPS/src/main.cpp
> +  float latitude = allDegrees + (allMinutes / 60);
fait

2024-04-30 15:01 UTC, AudeR22 commented on GPS/src/main.cpp
> +float getLongitude(char longData[], char longSign[]);
fait

2024-04-30 15:01 UTC, AudeR22 commented on GPS/src/main.cpp
> +    uint8_t dataSize = Serial1.readBytesUntil('\n', bufferGpsReceive, BUFFER_SIZE - 1);
fait

2024-04-30 15:01 UTC, AudeR22 commented on GPS/src/main.cpp
> +      const char *pGpsDataTest = gpsDataTest;
fait

2024-04-30 15:08 UTC, AudeR22 commented on GPS/src/main.cpp
> +      splitData(pGpsData);
fait

2024-04-30 15:09 UTC, AudeR22 commented on GPS/src/main.cpp
> +int splitData(const char *pGpsData)
Je retourne void

2024-04-30 18:21 UTC, AudeR22 commented on GPS/src/main.cpp
> +  if (pGpsData[0] == '\n' || pGpsData[0] == '\0' || pGpsData[0] != '$')
fait

2024-04-30 20:38 UTC, Pmichaud29 requested changes
Encore 2, 3 petites affaires et c'est good!

2024-04-30 20:38 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +    uint8_t i = 0;
pourrais être scoper dans le for

2024-04-30 20:38 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +    for (; pGpsData[i] != '\n' && pGpsData[i] != '\0' && i < BUFFER_SIZE && indexElements < NB_ELEMENTS && indexChar < SIZE_ELEMENTS; i++)
indexChar + 1 < SIZE_...

2024-04-30 20:38 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +  fixType = atoi(data[6]);
cast ton atoi en uint sinon tu as un risque d'overshoot

2024-04-30 20:38 UTC, Pmichaud29 commented on GPS/src/main.cpp
> +  if (fixType == 0)
0u

2024-05-01 18:56 UTC, Pmichaud29 approved these changes
Fait les test pour être sur que tout fonctionne encore avec le signal et sans le signal et ferme la pr mais merge pas (jva travailler dans ta branch pour le can)

2024-05-02 00:36 UTC, closed without merging